const express=require("express");
const auth=require("../middleware/authMiddleware");
const {createTask,getTasks,getTask,updateTask,deleteTask}=require("../controllers/taskController");
const router=express.Router();
router.use(auth);
router.post("/",createTask);
router.get("/",getTasks);
router.get("/:id",getTask);
router.put("/:id",updateTask);
router.delete("/:id",deleteTask);
module.exports=router;