import {useEffect,useState} from 'react'
const initial={title:'',description:'',status:'pending'}
export default function TaskForm({initialTask,submitLabel,onSubmit,submitting}){
 const [values,setValues]=useState(initial);const [errors,setErrors]=useState({})
 useEffect(()=>{if(initialTask)setValues({title:initialTask.title||'',description:initialTask.description||'',status:initialTask.status||'pending'})},[initialTask])
 const change=e=>{const {name,value}=e.target;setValues(v=>({...v,[name]:value}));setErrors(e=>({...e,[name]:''}))}
 const validate=()=>{const e={};if(!values.title.trim())e.title='Title is required.';if(values.title.trim().length>100)e.title='Title must be 100 characters or fewer.';if(values.description.length>500)e.description='Description must be 500 characters or fewer.';if(!['pending','in-progress','completed'].includes(values.status))e.status='Choose a valid status.';setErrors(e);return !Object.keys(e).length}
 const submit=e=>{e.preventDefault();if(validate())onSubmit({...values,title:values.title.trim(),description:values.description.trim()})}
 return <form className="form-card" onSubmit={submit} noValidate><div className="field"><label htmlFor="title">Task title</label><input id="title" name="title" value={values.title} onChange={change} placeholder="e.g. Complete API documentation"/>{errors.title&&<span className="field-error">{errors.title}</span>}</div><div className="field"><label htmlFor="description">Description</label><textarea id="description" name="description" rows="5" value={values.description} onChange={change} placeholder="Add a short description..."/>{errors.description&&<span className="field-error">{errors.description}</span>}</div><div className="field"><label htmlFor="status">Status</label><select id="status" name="status" value={values.status} onChange={change}><option value="pending">Pending</option><option value="in-progress">In Progress</option><option value="completed">Completed</option></select>{errors.status&&<span className="field-error">{errors.status}</span>}</div><button className="button primary full-width" disabled={submitting}>{submitting?'Saving...':submitLabel}</button></form>
}
